### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by pravirkr**
#### io module
- sigproc related functions are in the `io` module now. Removing the `back_compatible` option and using `sigproc_keys` (defined in [sigproc docs](http://sigproc.sourceforge.net/sigproc.pdf)) as the definition of a sigproc header.

#### Header
- Using [attrs](https://www.attrs.org/en/stable/#) for the new `Header` structure. The aim is to have a common header class read from different formats sigproc/psrfits/inf and write back. The header class is now more rigid compared to the earlier version, with property attributes handled accordingly. 
- One issue is that the output sigproc header size will be larger than the input, as we are using most of the sigproc keywords while writing to filterbanks.

#### C++
- Removing dependency on [fftw3](http://www.fftw.org/). Using numpy fft now (or [pyfftw](https://pyfftw.readthedocs.io/en/latest/) if available on the system).
- Moving all backend C++ code inside as `libcpp` module.

#### other
- module, class, and function names are now as per PEP 8. This will break the existing API.
- Moving `FilterbankBlock` to a separate module. `FoldedData` is now `foldedcube.` Renaming the `Filterbank` module to `base` (all readers should inherit from this base class).
- Support for command-line utilities (`spp_header` and `spp_decimate` for now). 
- Added more data files and tests.

### CODE REVIEW

**Comment by telegraphic** [comment]
Holy cow that is quite the refactor! 🕳️ 🐮 🕳️

**Comment by pravirkr** [comment]
Hi @telegraphic, the major change is in the `Header` class. The rest of them are just moving files and PEP 8 changes. There is no rush to merge this. I should also add the psrfits io to have a better idea about a common Header class design.

**Comment by pravirkr** [comment]
Hi @telegraphic, I am going ahead with the refactoring. The plan is to make this package an entirely python-based replacement of `sigproc`. Also, moving the core kernels from pybind11 to numba (easy to add new functions and no significant performance loss). Dependency on `fftw3` and `omp` is now external; easy to pip install. 

This will break the existing API. So, moving the current code to a legacy branch.

**Comment by telegraphic** [comment]
Glorious work! Python only seems reasonable, but bit unpacking might be difficult?

BTW, I suggest tagging a release & updating the README.md

🚀

**Comment by pravirkr** [comment]
bit unpacking powered by numpy/numba. 1 bit (`numpy.unpackbits`) is faster than numbits, whereas 2 and 4 bits (`numba`) are comparatively slower but acceptable.

Yes, need to update README.

**Pull request merged**
